# Usar uma imagem base do Node.js
FROM node:18 as build

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de configuração do projeto
COPY package.json package-lock.json ./

# Instalar as dependências
RUN npm install

# Copiar o restante dos arquivos do projeto
COPY . .

# Buildar a aplicação Angular
RUN npm run build -- --configuration=production

# Usar uma imagem leve do Nginx para servir a aplicação
FROM nginx:alpine

# Copiar os arquivos buildados para o Nginx
COPY --from=build /app/dist/nome-da-sua-app /usr/share/nginx/html

# Expor a porta 80
EXPOSE 4200

# Comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]